version: '3.5'

services:
  es:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "9200:9200"
    expose:
      - "9200"
    environment:
      - xpack.security.enabled=false
      - network.host=0.0.0.0
      - discovery.type=single-node
    volumes:
      - ./config/lemmagen:/usr/share/elasticsearch/config/lemmagen
      - ./config/stop-words:/usr/share/elasticsearch/config/stop-words
      - ./config/synonyms:/usr/share/elasticsearch/config/synonyms
